### ISSUE TITLE
boostsrl_data directory

### ISSUE THREAD

**Issue by batflyer** [batflyer/boostsrl-python-package#2]
From resolution to Issue #1:

> The current testing implementation requires the `boostsrl` directory to exist in two places (because of the jar's reliance on files being located in specific places). I'm adding Issue #2 as an issue introduced through this one's resolution.

Either create a folder in the user's home directory (similar to what nltk does) to store files, or something more elegant.

This will be useful for storing saved models, training/testing data, and background information.

**Comment by akohli96** [comment]
Do you plan on deploying this a python package?

**Comment by batflyer** [comment]
@akohli96 My verbose answer:

Getting a stable version with the necessary features is first priority, but long-term maintenance will be problematic for several reasons.

For example, the [training class of boostsrl.py](https://github.com/batflyer/boostsrl-python-package/blob/master/boostsrl/boostsrl.py):

```python
write_to_file(self.train_pos, 'boostsrl/train/train_pos.txt')
write_to_file(self.train_neg, 'boostsrl/train/train_neg.txt')
write_to_file(self.train_facts, 'boostsrl/train/train_facts.txt')

CALL = '(cd boostsrl; java -jar v1-0.jar -l -train train/ -target ' + self.target + ' -trees ' + str(self.trees) + ' > train_output.txt 2>&1)'
call_process(CALL)
```

The underlying design is a series of wrappers for a jar file, rather having standalone methods performing learning and inference. This is less of "BoostSRL in Python" and more of "Pythonic-BoostSRL to make writing code easier."

An easy-to-distribute package is less of a goal for these reasons:

1. The source is useless without the jar.
2. Potentially duplicate data (reading data from a file will simply store it elsewhere).
3. Platform independence will need to be taken into account (currently requires Linux).

Naturally these are subject to change, but most likely this will be distributed through GitHub or optionally with BoostSRL.

**Comment by akohli96** [comment]
One possibility is to expose boost-starai as REST apis and just make calls to it but that may be more effort than its worth

**Comment by batflyer** [comment]
Setting this issue to closed. Creating a specialized `boostsrl_data` directory causes problems upon install.
