### ISSUE TITLE
no module named subprocess32

### ISSUE THREAD

**Issue by kkroy36** [batflyer/boostsrl-python-package#4]
had to pip install module subprocess32 when it said "no module named subprocess32" the first time

**Comment by batflyer** [comment]
This is a requirement for running with Python 2, but as you already mentioned: `pip install subprocess32` is an easy fix.

I will leave this issue open for now and only close it when I put a requirements list on the README.

**Comment by batflyer** [comment]
README.md now includes:

Python 2:

```bash
$ pip install subprocess32
$ git clone https://github.com/batflyer/boostsrl-python-package.git
```

---

setup.py includes:
`install_requires = ['subprocess32'],`
