### ISSUE TITLE
Several things noticed during the RL run--arbitrary values can be passed to modes object

### ISSUE THREAD

**Issue by kkroy36** [batflyer/boostsrl-python-package#5]
1.The model and test object print statements didn't work. This maybe because it didn't learn anything (but using the jar calls it did work).

2. How to do multiple targets?

3. useStdLogicVariables default value? also currently set to 'True' which is a python keyword. Would be better to use lower case true and false as parameter settings I think. (When i did set it as "false", it still worked, so not sure what values exactly the argument can take).

**Comment by batflyer** [comment]
1. Can you include more detail (error messages, contents of backgrond.txt/train_output.txt/test_output.txt, or the code you ran)? Did you try to print an object itself, or did get_training_time/summarize_results return nothing? I need more information to know what the problem might be.

2. Multiple targets are not supported currently. It's worth mentioning that BoostSRL learns each target independently when specifying `-target t1,t2,t3`, so you can simulate multiple targets with something like the code below. If you have a specific use case in mind, feel free to submit an enhancement request as a separate issue.

```python
# Create separate backgrounds based on a particular target.
bk1 = boostsrl.modes(bk, 't1', ...)
bk2 = boostsrl.modes(bk, 't2', ...)
bk3 = boostsrl.modes(bk, 't3', ...)

# Then perform training/testing with separate targets.
model = boostsrl.train(bk1, ...)
results = boostsrl.test(model, ...)

model = boostsrl.train(bk2, ...)
# etc.
```

3. By default, useStdLogicVariables and usePrologVariables are False. All object parameters are either True or False for consistency between modes/train/test objects (for instance: why would advice=True, but usePrologVariables='true'?). Before writing to a background.txt, these values are converted to the notation used by BoostSRL (refer to boostsrl.py lines 104-117).

**Comment by batflyer** [comment]
Refer to Issue #6 for point 2.

**Comment by batflyer** [comment]
Solved Error-1 offline, Error-2 was moved to its own issue, this issue is now classified as a bug: need to write tests to make sure arbitrary values are not passed into the modes object.

```python
# Currently, this:
background = boostsrl.modes(bk, 'cancer', useStdLogicVariables=True)
# Functions identically to this (but shouldn't)
background = boostsrl.modes(bk, 'cancer', useStdLogicVariables='true')
```

**Comment by batflyer** [comment]
A more elegant way to do this seems to be of discussion in [PEP 3107](https://www.python.org/dev/peps/pep-3107/), a consistent method for Python 2/3 to at least check that values are of an acceptable type was added, code copied below.

```python
types = {
    'background should be a list.': isinstance(background, list),
    'target should be a list.': isinstance(target, list),
    'bridgers should be a list.': isinstance(bridgers, list) or bridgers is None,
    'precomputes should be a dictionary.': isinstance(precomputes, dict) or precomputes is None,
    'loadAllLibraries should be boolean.': isinstance(loadAllLibraries, bool),
    'useStdLogicVariables should be boolean.': isinstance(useStdLogicVariables, bool),
    'usePrologVariables should be boolean.': isinstance(usePrologVariables, bool),
    'recursion should be boolean.': isinstance(recursion, bool),
    'lineSearch should be boolean.': isinstance(lineSearch, bool),
    'resampleNegs should be boolean.': isinstance(resampleNegs, bool),
    'treeDepth should be an int.': isinstance(treeDepth, int) or treeDepth is None,
    'maxTreeDepth should be an int.': isinstance(maxTreeDepth, int) or maxTreeDepth is None,
    'nodeSize should be an int.': isinstance(nodeSize, int) or nodeSize is None,
    'numOfClause should be an int.': isinstance(numOfClauses, int) or numOfClauses is None,
    'numOfCycles should be an int.': isinstance(numOfCycles, int) or numOfCycles is None,
    'minLCTrees should be an int.': isinstance(minLCTrees, int) or minLCTrees is None,
    'incrLCTrees should be an int.': isinstance(incrLCTrees, int) or incrLCTrees is None
}
        
# Force type checking for input validation Issue #5
for type_check in types:
    if not types[type_check]:
        raise(TypeError('Error when checking type: ' +  type_check))
```
